project_name: Day3
username: frizzerdk

is_sweep: False


preprocessed_data_path: ./data/preprocessed
x_train_path: ${preprocessed_data_path}/x_train.npy
y_train_path: ${preprocessed_data_path}/y_train.npy
x_test_path: ${preprocessed_data_path}/x_test.npy
x_val_path: ${preprocessed_data_path}/x_val.npy
y_val_path: ${preprocessed_data_path}/y_val.npy

checkpoint_path: ./checkpoints
best_model_path: ${checkpoint_path}/best_model.keras

num_classes: 10
input_shape: [28, 28, 1]

activation: relu

epochs: 100
param_scale: 2.0
dropout_rate: 0.1
learning_rate: 0.0003
batch_size: 64
patience: 20

# Configuration for data augmentation layers with both positional and keyword arguments
data_augmentation:
  layers:
    # RandomCrop:
    #   args: [32, 32]           
    # RandomFlip:
    #   kwargs:
    #     mode: "horizontal_and_vertical"
    RandomTranslation:
      kwargs:
        height_factor: 0.2
        width_factor: 0.2
        fill_mode: "constant"
    RandomRotation:
      kwargs:
        factor: 0.2
        fill_mode: "constant"           
    RandomZoom:
      kwargs:
        height_factor: 0.2
        width_factor: 0.2
        fill_mode: "constant"
    RandomContrast:
      kwargs:
        factor: 0.2       
    RandomBrightness:
      kwargs:
        factor: 0.5
        value_range: [0.0, 1.0]
