project_name: quadbot_chaser_ppo
username: frizzerdk

env:
  name: QuadChaseEnv
  max_steps: 1000
  frame_skip: 5
  render_mode: ""
  xml_file: "quadbot.xml"

  observation_max_wheel_steer_vel: 5
  observation_max_wheel_drive_vel: 100
  observation_max_body_linear_vel: 20
  observation_max_body_angular_vel: 3
  observation_max_body_position: 10
  steer_joint_damping: 0.1
  drive_joint_damping: 0.05
  steer_actuator_gain: 2
  drive_actuator_gain: 3
  reset_noise_scale: 1
  reset_pos_offset: 2
  target_pos_distance: 3
  reward_scale_action_penalty: 0.1
  reward_scale_wheel_misalignment: 1.0
  reward_scale_position_penalty: 1.0
  reward_scale_success_reward: 10
  wheel_alignment_threshold: 10
  reward_scale_total: 1.0
  steer_kp: 10
  
model:
  policy: MlpPolicy
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.001
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: true
  sde_sample_freq: -1
  hidden_layers_size: 256

train:
  total_timesteps: 5000000
  log_interval: 1
  eval_freq: 500000
  n_eval_episodes: 5
  deterministic_eval: true
  render_eval: true

save:
  model_dir: ./models
  save_freq: 50000

monitor_dir: ./monitor/
video_dir: ./video
log_dir: ./logs
checkpoint_path: ./checkpoints
is_sweep: false
