project_name: quadbot_ppo
username: frizzerdk

env:
  name: QuadbotEnv
  max_steps: 1000
  frame_skip: 5
  render_mode: "human"

model:
  policy: MlpPolicy
  learning_rate: 0.0003
  n_steps: 4096
  batch_size: 64
  n_epochs: 10
  gamma: 0.999
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0001
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: true
train:
  total_timesteps: 50000000
  log_interval: 1
  eval_freq: 100000
  n_eval_episodes: 5
  deterministic_eval: false
  render_eval: true
  render_delay: 0.01

save:
  model_dir: ./quadbot_models
  save_freq: 50000

monitor_dir: ./quadbot_monitor
video_dir: ./quadbot_video
log_dir: ./quadbot_logs
checkpoint_path: ./quadbot_checkpoints
is_sweep: false