project_name: quadbot_ppo
username: frizzerdk

env:
  name: QuadbotEnv
  max_steps: 500
  frame_skip: 5
  render_mode: "human"
  xml_file: "quadbot.xml"
  reset_noise_scale: 0.1
  default_camera_config:
    distance: 15
  initial_conditions:
    body_pos_noise_scale: [50.0, 50.0, 0.0]
    body_orientation_noise_scale: 0.01
    slide_joint_noise_scale: 0.001
    steer_joint_noise_scale: 0.001
    drive_joint_noise_scale: 0.001
    velocity_noise_scale: 0.001
  reward_weights:
    x_velocity: 1.0
    y_velocity_penalty: 0.1
    body_rotation_penalty: 0.01
    steer_penalty: 0.1
    drive_penalty: 1.0
    actuation_penalty: 1.0
    wheel_misalignment_penalty: 1.0
  reward_scales:
    primary: 0.01
    secondary: 0.01
  termination:
    min_height: 0.01

model:
  policy: MlpPolicy
  learning_rate: 0.0003
  n_steps: 4096
  batch_size: 64
  n_epochs: 10
  gamma: 0.999
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.1
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: true

train:
  total_timesteps: 3000000
  log_interval: 1
  eval_freq: 500000
  n_eval_episodes: 2
  deterministic_eval: true
  render_eval: true

save:
  model_dir: ./quadbot_models
  save_freq: 50000

monitor_dir: ./quadbot_monitor
video_dir: ./quadbot_video
log_dir: ./quadbot_logs
checkpoint_path: ./quadbot_checkpoints
is_sweep: false
